name: CI Pipeline - Testes Automatizados

# Define quando o pipeline ser치 acionado
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar c칩digo do reposit칩rio
        uses: actions/checkout@v4

      - name: Configurar o Python no Runner
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar o Pytest
        run: pip install pytest

      - name: Executar os testes unit치rios
        run: pytest